---
abstract: 'encode characters for LaTeX formatting'
author:
  - 'Chris Travers <chris@efficito.com>'
build_requires:
  Carp::Always: 0
  Test::More: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LaTeX-Encode
no_index:
  directory:
    - t
    - inc
requires:
  Getopt::Long: 0
  HTML::Entities: 0
  Pod::LaTeX: 0
  Pod::Usage: 0
  Readonly: 0
resources:
  repository: https://github.com/einhverfr/LaTeX-Encode.git
version: v0.091.6
