---
abstract: 'encode characters for LaTeX formatting'
author:
  - 'Andrew Ford <a.ford@ford-mason.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LaTeX-Encode
no_index:
  directory:
    - t
    - inc
requires:
  Getopt::Long: 0
  HTML::Entities: 0
  Pod::LaTeX: 0
  Pod::Usage: 0
  Readonly: 0
  Test::More: 0
version: 0.08
